#!/bin/bash
# .husky/pre-commit

# Exit on error
set -e

# Run lint-staged first (your existing pre-commit tasks)
#pnpm lint-staged

# Run prepare-template.sh
./scripts/prepare-template.sh

# Add the template directory changes to the commit
git add template/
